server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: framework
  use-forward-headers: true
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: ".*"

spring:
  application:
    name: auth-service
  profiles:
    active: dev   # default profile, can be overridden by ENV var

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

event:
  exchange: ${EVENT_EXCHANGE:gymai.events}
  routing:
    registration: ${REGISTRATION_ROUTING_KEY:user.registration}
    login: ${LOGIN_ROUTING_KEY:user.login}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

logging:
  file:
    name: ${LOG_FILE:logs/auth-service.log}
  level:
    root: INFO
    com.gymai.auth_service: DEBUG

app:
  frontend:
    default-url: https://gymai.neelahouse.cloud
    allowed-urls: >
      https://gymai.neelahouse.cloud,
      https://gymaibybhawesh.netlify.app,
      https://gymaibybhawesh.vercel.app,
      http://localhost:4200
