spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_ai
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  web:
    cors:
      allowed-origins:
        - "http://localhost:4200"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

  rabbitmq:
    addresses: ${CLOUDAMQP_URL}
    ssl:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: ${REDIRECT_URI}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
            redirect-uri: ${REDIRECT_URI}
