server:
  port: 8085

spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092

kafka:
  topic:
    notification: notification_topic
