server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: plan-service
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://ep-damp-star-ab0lcdvm-pooler.eu-west-2.aws.neon.tech/gym_ai?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_5PnAXGO6FLUt
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

jwt:
  secret: 7ace60a838bde7dc46e8065031ee2ccfba62cb79d5b1b4642fa50a0b88f78efc
  expiration: 3600000 # 1 hour in ms

logging:
  file:
    name: logs/plan-service.log
  level:
    root: INFO
    # com.gymai.user_service: DEBUG  # Changed from auth_service to user_service
    # com.gymai.plan_service.feign.SpoonacularClient: DEBUG
    # feign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http: TRACE
    org.hibernate.SQL: WARN

ai:
  service:
    url: http://localhost:8000
user:
  service:
    url: http://localhost:8082

wger:
  api-url: https://wger.de/api/v2

spoonacular:
  api-url: https://api.spoonacular.com
  api:
    key: 37dbf57de68f4d79967bf7ac9c0490e5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
