spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:5432/gym_ai}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  data:
    redis:
      url: ${REDIS_URL}
      timeout: ${REDIS_TIMEOUT:5000ms}
      database: ${REDIS_DATABASE:0}
      ssl:
        enabled: true
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 2000ms
        shutdown-timeout: 100ms
