spring:
  application:
    name: tracking-service
  datasource:
    url: ${TRACKING_DB_URL}
    username: ${TRACKING_DB_USER}
    password: ${TRACKING_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${TRACKING_JPA_DDL_AUTO:update}
    show-sql: ${TRACKING_SHOW_SQL:false}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
