server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: plan-service
          uri: lb://plan-service
          predicates:
            - Path=/api/plans/**

        - id: progress-service
          uri: lb://progress-service
          predicates:
            - Path=/api/progress/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notify/**

        - id: ai-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/ai/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
