server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://ep-damp-star-ab0lcdvm-pooler.eu-west-2.aws.neon.tech/gym_ai?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_5PnAXGO6FLUt
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  rabbitmq:
    addresses: ${CLOUDAMQP_URL:amqps://dnqrhfau:MW512Q4X9oZqYYEmiv2ZnhgG42QS3nOS@puffin.rmq2.cloudamqp.com/dnqrhfau}
    ssl:
      enabled: true # CloudAMQP requires SSL (amqps)

jwt:
  secret: 7ace60a838bde7dc46e8065031ee2ccfba62cb79d5b1b4642fa50a0b88f78efc
  expiration: 3600000

# Eureka (optional: remove if not used)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/user-service.log
  level:
    root: INFO
    com.gymai.user_service: DEBUG

feign:
  client:
    config:
      auth-service:
        url: ${ADMIN_URL:http://localhost:8081}

rabbit:
  exchange: gym.exchange
  routing-key: user.event
  queue: user.events.queue
